### PR TITLE
Fix string

### PR DESCRIPTION
**Pull request by Loki-Astari**
Fix a couple of likely bugs.

Also added a more modern interface.

I would be very surprised if this is any near as efficient as std::string.
Do you actually have tests/benchmarks to show this helps?

### CODE REVIEW

**Comment by SuperFola** [comment]
> I would be very surprised if this is any near as efficient as std::string.
> Do you actually have tests/benchmarks to show this helps?

It isn't as fast as std::string, but it's twice smaller, which helps keeping the `Ark::Value` size low (the types are in a std::variant, with +8 overhead, so with a std::string we would get 32+8)

**Comment by SuperFola** [comment]
This gave me food for thoughts, and we should try to bench ArkScript with the String and with std::string ; two things should be mesured: bench time and memory consumption, if the ratio Δbench / Δmemory is correct (ie if we get more perf than we loose RAM) then just ditch the String

**Comment by Loki-Astari** [comment]
Most std::string implementations are 3 pointers so `24 bytes`.
So yes there is a slight increase in size from your `16 byte` version.

But if you look at the `Value` object there are already three types in there that are already 24 bytes in size.
So the total size of `Value` is not going to increase.

**Comment by Loki-Astari** [comment]
While you think about it.
You should push this commit as it fixes a bug with empty strings (which may be the cause of some of your issues with untraceable crashes).

**Comment by SuperFola** [comment]
> Most std::string implementations are 3 pointers so 24 bytes.
> So yes there is a slight increase in size from your 16 byte version.

Woops, I got it wrong then.

You're right, we can get this merge for now and ditch this later on.

**Review by SuperFola — APPROVED** [review]

**Pull request merged**
